#ifndef _UR_FIELDS_H_
#define _UR_FIELDS_H_

/************* THIS IS AUTOMATICALLY GENERATED FILE, DO NOT EDIT *************/
#include <unirec/unirec.h>

#define F_ACK_C   0
#define F_ACK_C_T   double
#define F_ACK_COUNT   1
#define F_ACK_COUNT_T   double
#define F_ACK_WAITING   2
#define F_ACK_WAITING_T   double
#define F_ACL_MTU   3
#define F_ACL_MTU_T   double
#define F_ACL_PACKETS   4
#define F_ACL_PACKETS_T   double
#define F_ADDRESS   5
#define F_ADDRESS_T   double
#define F_AVERAGE   6
#define F_AVERAGE_T   double
#define F_AVERAGE_REQUEST_RTT   7
#define F_AVERAGE_REQUEST_RTT_T   double
#define F_AVERAGE_RESPONSE_RTT   8
#define F_AVERAGE_RESPONSE_RTT_T   double
#define F_BAD_CHECKSUM   9
#define F_BAD_CHECKSUM_T   double
#define F_BAD_ROUTES   10
#define F_BAD_ROUTES_T   double
#define F_BROADCAST_C   11
#define F_BROADCAST_C_T   double
#define F_BROADCAST_READ_COUNT   12
#define F_BROADCAST_READ_COUNT_T   double
#define F_BROADCAST_WRITE_COUNT   13
#define F_BROADCAST_WRITE_COUNT_T   double
#define F_BYTE   14
#define F_BYTE_T   double
#define F_CALLBACKS   15
#define F_CALLBACKS_T   double
#define F_CAN_COUNT   16
#define F_CAN_COUNT_T   double
#define F_CMDCLASS   17
#define F_CMDCLASS_T   double
#define F_CORRUPTED_C   18
#define F_CORRUPTED_C_T   double
#define F_CORRUPTED_CH1_C   19
#define F_CORRUPTED_CH1_C_T   double
#define F_CORRUPTED_CH2_C   20
#define F_CORRUPTED_CH2_C_T   double
#define F_CORRUPTED_CH3_C   21
#define F_CORRUPTED_CH3_C_T   double
#define F_DEV_ADDR   22
#define F_DEV_ADDR_T   uint64_t
#define F_DROPPED   23
#define F_DROPPED_T   double
#define F_DST_ACK_C   24
#define F_DST_ACK_C_T   double
#define F_DST_NACK_C   25
#define F_DST_NACK_C_T   double
#define F_DST_SINGL_C   26
#define F_DST_SINGL_C_T   double
#define F_DST_SINGL_LM_T   27
#define F_DST_SINGL_LM_T_T   double
#define F_DST_TOTAL_C   28
#define F_DST_TOTAL_C_T   double
#define F_DST_TOTAL_LM_T   29
#define F_DST_TOTAL_LM_T_T   double
#define F_ERR_VALUE   30
#define F_ERR_VALUE_T   double
#define F_EVENT_TYPE   31
#define F_EVENT_TYPE_T   double
#define F_FAILED_HOP_NACK_C   32
#define F_FAILED_HOP_NACK_C_T   double
#define F_GENRE   33
#define F_GENRE_T   double
#define F_GW_ID   34
#define F_GW_ID_T   double
#define F_HOME_ID   35
#define F_HOME_ID_T   double
#define F_INCIDENT_DEV_ADDR   36
#define F_INCIDENT_DEV_ADDR_T   uint64_t
#define F_INDEX   37
#define F_INDEX_T   double
#define F_INSTANCE   38
#define F_INSTANCE_T   double
#define F_LAST_REQUEST_RTT   39
#define F_LAST_REQUEST_RTT_T   double
#define F_LAST_RESPONSE_RTT   40
#define F_LAST_RESPONSE_RTT_T   double
#define F_MESSAGE_TYPE   41
#define F_MESSAGE_TYPE_T   double
#define F_MOVING_AVERAGE   42
#define F_MOVING_AVERAGE_T   double
#define F_MOVING_MEDIAN   43
#define F_MOVING_MEDIAN_T   double
#define F_MOVING_VARIANCE   44
#define F_MOVING_VARIANCE_T   double
#define F_MULTICAST_C   45
#define F_MULTICAST_C_T   double
#define F_NAK_COUNT   46
#define F_NAK_COUNT_T   double
#define F_NET_BUSY   47
#define F_NET_BUSY_T   double
#define F_NET_MANAG_C   48
#define F_NET_MANAG_C_T   double
#define F_NO_ACK   49
#define F_NO_ACK_T   double
#define F_NODE_ID   50
#define F_NODE_ID_T   double
#define F_NON_DELIVERY   51
#define F_NON_DELIVERY_T   double
#define F_NOT_IDLE   52
#define F_NOT_IDLE_T   double
#define F_OOF_COUNT   53
#define F_OOF_COUNT_T   double
#define F_PROFILE_VALUE   54
#define F_PROFILE_VALUE_T   double
#define F_QUALITY   55
#define F_QUALITY_T   double
#define F_READ_ABORTS   56
#define F_READ_ABORTS_T   double
#define F_READ_COUNT   57
#define F_READ_COUNT_T   double
#define F_RECEIVED_COUNT   58
#define F_RECEIVED_COUNT_T   double
#define F_RECEIVE_DUPLICATIONS   59
#define F_RECEIVE_DUPLICATIONS_T   double
#define F_RECEIVE_UNSOLICITED   60
#define F_RECEIVE_UNSOLICITED_T   double
#define F_RETRIES   61
#define F_RETRIES_T   double
#define F_ROUTED_ACK_C   62
#define F_ROUTED_ACK_C_T   double
#define F_ROUTED_APP_C   63
#define F_ROUTED_APP_C_T   double
#define F_ROUTED_BUSY   64
#define F_ROUTED_BUSY_T   double
#define F_ROUTED_C   65
#define F_ROUTED_C_T   double
#define F_ROUTED_NACK_C   66
#define F_ROUTED_NACK_C_T   double
#define F_RSSI   67
#define F_RSSI_T   double
#define F_RX_ACLS   68
#define F_RX_ACLS_T   double
#define F_RX_BYTES   69
#define F_RX_BYTES_T   double
#define F_RX_ERRORS   70
#define F_RX_ERRORS_T   double
#define F_RX_EVENTS   71
#define F_RX_EVENTS_T   double
#define F_RX_SCOS   72
#define F_RX_SCOS_T   double
#define F_SCO_MTU   73
#define F_SCO_MTU_T   double
#define F_SCO_PACKETS   74
#define F_SCO_PACKETS_T   double
#define F_SENT_COUNT   75
#define F_SENT_COUNT_T   double
#define F_SENT_FAILED   76
#define F_SENT_FAILED_T   double
#define F_SINGLECAST_C   77
#define F_SINGLECAST_C_T   double
#define F_SIZE   78
#define F_SIZE_T   double
#define F_SOF_COUNT   79
#define F_SOF_COUNT_T   double
#define F_SRC_ACK_C   80
#define F_SRC_ACK_C_T   double
#define F_SRC_BROADCAST_C   81
#define F_SRC_BROADCAST_C_T   double
#define F_SRC_MULTICAST_C   82
#define F_SRC_MULTICAST_C_T   double
#define F_SRC_NACK_C   83
#define F_SRC_NACK_C_T   double
#define F_SRC_SINGL_C   84
#define F_SRC_SINGL_C_T   double
#define F_SRC_SINGL_LM_T   85
#define F_SRC_SINGL_LM_T_T   double
#define F_SRC_TOTAL_C   86
#define F_SRC_TOTAL_C_T   double
#define F_SRC_TOTAL_LM_T   87
#define F_SRC_TOTAL_LM_T_T   double
#define F_TIMESTAMP   88
#define F_TIMESTAMP_T   ur_time_t
#define F_TOTAL_OK_C   89
#define F_TOTAL_OK_C_T   double
#define F_TX_ACLS   90
#define F_TX_ACLS_T   double
#define F_TX_BYTES   91
#define F_TX_BYTES_T   double
#define F_TX_CMDS   92
#define F_TX_CMDS_T   double
#define F_TX_ERRORS   93
#define F_TX_ERRORS_T   double
#define F_TX_SCOS   94
#define F_TX_SCOS_T   double
#define F_TYPE   95
#define F_TYPE_T   double
#define F_VALUE   96
#define F_VALUE_T   double
#define F_WRITE_COUNT   97
#define F_WRITE_COUNT_T   double
#define F_ALERT_CODE   98
#define F_ALERT_CODE_T   uint32_t
#define F_ALERT_DESC   99
#define F_ALERT_DESC_T   char
#define F_CAPTION   100
#define F_CAPTION_T   char
#define F_CHANNELS   101
#define F_CHANNELS_T   char
#define F_CMD   102
#define F_CMD_T   char
#define F_EVENT   103
#define F_EVENT_T   char
#define F_MSG_TYPE   104
#define F_MSG_TYPE_T   char
#define F_PAYLOAD   105
#define F_PAYLOAD_T   char
#define F_PROFILE_KEY   106
#define F_PROFILE_KEY_T   char
#define F_PROT_STATE   107
#define F_PROT_STATE_T   char
#define F_RAW_PAYLOAD   108
#define F_RAW_PAYLOAD_T   char
#define F_UR_KEY   109
#define F_UR_KEY_T   char

extern uint16_t ur_last_id;
extern ur_static_field_specs_t UR_FIELD_SPECS_STATIC;
extern ur_field_specs_t ur_field_specs;

#endif

